server:
  port: 8083
spring:
  application:
    name: orchestrator-service
  profiles:
    active: prod
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true