import requests
import os
import time

# GitHub API configuration
REPO = "dineshkumarssundaram/Software-Factory"
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")  # Set this as an environment variable or replace with your token
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}
API_URL = f"https://api.github.com/repos/{REPO}/issues"

# List of all 300 issues (combined from High-Level, Low-Level, and Spring Boot categories)
issues = [
    # High-Level System Design (100+ Issues)
    "Propose a high-level architecture for integrating Spring-based microservices with a service discovery layer.",
    "Design a high-level system for API gateway routing in a Spring Boot application.",
    "Suggest a high-level plan for load balancing across Spring services.",
    "Create an issue for designing a high-level fault tolerance strategy for the backend.",
    "Propose a high-level architecture for a centralized configuration server.",
    "Design a high-level system for inter-service communication using REST APIs.",
    "Suggest a high-level plan for monitoring Spring microservices.",
    "Create an issue for designing a high-level data flow between services.",
    "Propose a high-level architecture for a service repository management system.",
    "Design a high-level system for handling API versioning.",
    "Suggest a high-level plan for disaster recovery in the backend.",
    "Create an issue for designing a high-level security model for APIs.",
    "Propose a high-level architecture for a distributed caching layer.",
    "Design a high-level system for service discovery failover.",
    "Suggest a high-level plan for scalability of Spring services.",
    "Create an issue for designing a high-level logging strategy.",
    "Propose a high-level architecture for message queuing between services.",
    "Design a high-level system for rate limiting APIs.",
    "Suggest a high-level plan for CI/CD pipeline integration.",
    "Create an issue for designing a high-level authentication flow.",
    "Propose a high-level architecture for a multi-tenant backend.",
    "Design a high-level system for service health checks.",
    "Suggest a high-level plan for data consistency across services.",
    "Create an issue for designing a high-level deployment strategy.",
    "Propose a high-level architecture for a global CDN integration.",
    "Design a high-level system for API analytics collection.",
    "Suggest a high-level plan for service orchestration.",
    "Create an issue for designing a high-level error handling framework.",
    "Propose a high-level architecture for a hybrid cloud setup.",
    "Design a high-level system for cross-region data replication.",
    "Suggest a high-level plan for backup and restore procedures.",
    "Create an issue for designing a high-level audit logging system.",
    "Propose a high-level architecture for a service mesh integration.",
    "Design a high-level system for API throttling.",
    "Suggest a high-level plan for capacity planning.",
    "Create an issue for designing a high-level resilience pattern.",
    "Propose a high-level architecture for a multi-protocol API gateway.",
    "Design a high-level system for service versioning.",
    "Suggest a high-level plan for disaster recovery testing.",
    "Create an issue for designing a high-level observability framework.",
    "Propose a high-level architecture for a federated identity system.",
    "Design a high-level system for service dependency mapping.",
    "Suggest a high-level plan for zero-downtime deployments.",
    "Create an issue for designing a high-level data governance model.",
    "Propose a high-level architecture for a global load balancer.",
    "Design a high-level system for API security auditing.",
    "Suggest a high-level plan for service lifecycle management.",
    "Create an issue for designing a high-level event-driven architecture.",
    "Propose a high-level architecture for a multi-region database.",
    "Design a high-level system for service discovery scalability.",
    "Suggest a high-level plan for performance benchmarking.",
    "Create an issue for designing a high-level compliance framework.",
    "Propose a high-level architecture for a service registry backup.",
    "Design a high-level system for API rate monitoring.",
    "Suggest a high-level plan for service degradation handling.",
    "Create an issue for designing a high-level retry mechanism.",
    "Propose a high-level architecture for a circuit breaker pattern.",
    "Design a high-level system for cross-service authentication.",
    "Suggest a high-level plan for service discovery monitoring.",
    "Create an issue for designing a high-level data migration strategy.",
    "Propose a high-level architecture for a global API gateway.",
    "Design a high-level system for service health reporting.",
    "Suggest a high-level plan for load testing the backend.",
    "Create an issue for designing a high-level security patch process.",
    "Propose a high-level architecture for a distributed tracing system.",
    "Design a high-level system for API endpoint consolidation.",
    "Suggest a high-level plan for service discovery failover testing.",
    "Create an issue for designing a high-level data retention policy.",
    "Propose a high-level architecture for a multi-cluster setup.",
    "Design a high-level system for service dependency resolution.",
    "Suggest a high-level plan for API usage analytics.",
    "Create an issue for designing a high-level backup validation process.",
    "Propose a high-level architecture for a service mesh security.",
    "Design a high-level system for cross-region load balancing.",
    "Suggest a high-level plan for service discovery optimization.",
    "Create an issue for designing a high-level incident response plan.",
    "Propose a high-level architecture for a multi-tenant database.",
    "Design a high-level system for API performance monitoring.",
    "Suggest a high-level plan for service registry synchronization.",
    "Create an issue for designing a high-level data encryption strategy.",
    "Propose a high-level architecture for a global service discovery.",
    "Design a high-level system for API error tracking.",
    "Suggest a high-level plan for service degradation testing.",
    "Create an issue for designing a high-level resilience testing.",
    "Propose a high-level architecture for a distributed logging system.",
    "Design a high-level system for service health aggregation.",
    "Suggest a high-level plan for API security compliance.",
    "Create an issue for designing a high-level data synchronization.",
    "Propose a high-level architecture for a multi-protocol service bus.",
    "Design a high-level system for service discovery auditing.",
    "Suggest a high-level plan for load balancer configuration.",
    "Create an issue for designing a high-level disaster recovery drill.",
    "Propose a high-level architecture for a global caching layer.",
    "Design a high-level system for API usage reporting.",
    "Suggest a high-level plan for service dependency testing.",
    "Create an issue for designing a high-level security audit process.",
    "Propose a high-level architecture for a multi-region service mesh.",
    "Design a high-level system for service discovery health checks.",
    "Suggest a high-level plan for performance optimization strategy.",
    "Create an issue for designing a high-level compliance audit plan.",
    "Propose a high-level architecture for a distributed API gateway.",
    "Design a high-level system for service lifecycle auditing.",
    "Suggest a high-level plan for zero-downtime migration.",

    # Low-Level System Design (100+ Issues)
    "Create an issue for designing a low-level module for Spring Boot API authentication.",
    "Propose a low-level design for a service discovery client in Java.",
    "Design a low-level system for handling REST API request validation.",
    "Suggest a low-level plan for implementing a circuit breaker in Spring.",
    "Create an issue for designing a low-level caching layer for Java services.",
    "Propose a low-level design for a service repository database schema.",
    "Design a low-level system for logging API calls in Spring Boot.",
    "Suggest a low-level plan for implementing rate limiting in Java.",
    "Create an issue for designing a low-level error handling mechanism.",
    "Propose a low-level design for a Spring Boot configuration loader.",
    "Design a low-level system for service health check endpoints.",
    "Suggest a low-level plan for implementing retry logic in Java.",
    "Create an issue for designing a low-level data serialization layer.",
    "Propose a low-level design for a Spring Boot scheduler.",
    "Design a low-level system for API response caching.",
    "Suggest a low-level plan for implementing a load balancer client.",
    "Create an issue for designing a low-level authentication filter.",
    "Propose a low-level design for a service discovery heartbeat.",
    "Design a low-level system for handling API timeouts.",
    "Suggest a low-level plan for implementing a message queue consumer.",
    "Create an issue for designing a low-level data validation service.",
    "Propose a low-level design for a Spring Boot REST controller.",
    "Design a low-level system for service registration in Eureka.",
    "Suggest a low-level plan for implementing a circuit breaker fallback.",
    "Create an issue for designing a low-level logging interceptor.",
    "Propose a low-level design for a Spring Boot exception handler.",
    "Design a low-level system for API request throttling.",
    "Suggest a low-level plan for implementing a cache eviction policy.",
    "Create an issue for designing a low-level service discovery cache.",
    "Propose a low-level design for a Spring Boot task executor.",
    "Design a low-level system for handling API rate limits.",
    "Suggest a low-level plan for implementing a retry backoff strategy.",
    "Create an issue for designing a low-level data mapping layer.",
    "Propose a low-level design for a Spring Boot API gateway filter.",
    "Design a low-level system for service discovery polling.",
    "Suggest a low-level plan for implementing a load balancer health check.",
    "Create an issue for designing a low-level authentication token generator.",
    "Propose a low-level design for a Spring Boot event listener.",
    "Design a low-level system for API error response formatting.",
    "Suggest a low-level plan for implementing a message queue producer.",
    "Create an issue for designing a low-level data encryption service.",
    "Propose a low-level design for a Spring Boot REST client.",
    "Design a low-level system for service registration validation.",
    "Suggest a low-level plan for implementing a circuit breaker timeout.",
    "Create an issue for designing a low-level logging configuration.",
    "Propose a low-level design for a Spring Boot scheduler task.",
    "Design a low-level system for API request logging.",
    "Suggest a low-level plan for implementing a cache refresh mechanism.",
    "Create an issue for designing a low-level service discovery filter.",
    "Propose a low-level design for a Spring Boot exception mapper.",
    "Design a low-level system for handling API concurrency.",
    "Suggest a low-level plan for implementing a load balancer retry.",
    "Create an issue for designing a low-level authentication validator.",
    "Propose a low-level design for a Spring Boot API interceptor.",
    "Design a low-level system for service discovery timeout handling.",
    "Suggest a low-level plan for implementing a message queue retry.",
    "Create an issue for designing a low-level data transformation layer.",
    "Propose a low-level design for a Spring Boot REST endpoint.",
    "Design a low-level system for service registration heartbeat.",
    "Suggest a low-level plan for implementing a circuit breaker state.",
    "Create an issue for designing a low-level logging filter.",
    "Propose a low-level design for a Spring Boot task scheduler.",
    "Design a low-level system for API response validation.",
    "Suggest a low-level plan for implementing a cache invalidation.",
    "Create an issue for designing a low-level service discovery client.",
    "Propose a low-level design for a Spring Boot API filter.",
    "Design a low-level system for handling API retries.",
    "Suggest a low-level plan for implementing a load balancer failover.",
    "Create an issue for designing a low-level authentication service.",
    "Propose a low-level design for a Spring Boot event publisher.",
    "Design a low-level system for service discovery error handling.",
    "Suggest a low-level plan for implementing a message queue consumer.",
    "Create an issue for designing a low-level data compression layer.",
    "Propose a low-level design for a Spring Boot REST proxy.",
    "Design a low-level system for service registration polling.",
    "Suggest a low-level plan for implementing a circuit breaker reset.",
    "Create an issue for designing a low-level logging aggregator.",
    "Propose a low-level design for a Spring Boot scheduler trigger.",
    "Design a low-level system for API request validation.",
    "Suggest a low-level plan for implementing a cache preload.",
    "Create an issue for designing a low-level service discovery proxy.",
    "Propose a low-level design for a Spring Boot API handler.",
    "Design a low-level system for handling API timeouts.",
    "Suggest a low-level plan for implementing a load balancer health probe.",
    "Create an issue for designing a low-level authentication encoder.",
    "Propose a low-level design for a Spring Boot event subscriber.",
    "Design a low-level system for service discovery caching.",
    "Suggest a low-level plan for implementing a message queue scheduler.",
    "Create an issue for designing a low-level data parsing layer.",
    "Propose a low-level design for a Spring Boot REST service.",
    "Design a low-level system for service registration validation.",
    "Suggest a low-level plan for implementing a circuit breaker monitor.",
    "Create an issue for designing a low-level logging parser.",
    "Propose a low-level design for a Spring Boot task runner.",
    "Design a low-level system for API response caching.",
    "Suggest a low-level plan for implementing a cache refresh interval.",
    "Create an issue for designing a low-level service discovery monitor.",
    "Propose a low-level design for a Spring Boot API validator.",
    "Design a low-level system for handling API concurrency limits.",
    "Suggest a low-level plan for implementing a load balancer retry policy.",

    # Spring Boot/Backend/Java-Specific Issues (100+ Issues)
    "Report a bug where Spring Boot fails to initialize the service discovery client.",
    "Create an issue for a bug where Java API endpoints return 500 errors.",
    "Propose a feature to add Spring Boot actuator endpoints for custom metrics.",
    "Report a bug where the Spring Boot app crashes on high load.",
    "Create an issue for a bug where Java serialization fails for complex objects.",
    "Propose a feature to implement Spring Security for API endpoints.",
    "Report a bug where the Spring Boot scheduler misses tasks.",
    "Create an issue for a bug where Java memory usage spikes unexpectedly.",
    "Propose a feature to add Spring Data JPA for database operations.",
    "Report a bug where the Spring Boot API gateway drops requests.",
    "Create an issue for a bug where Java threads deadlock during API calls.",
    "Propose a feature to implement Spring Kafka for message processing.",
    "Report a bug where the Spring Boot app fails to connect to Eureka.",
    "Create an issue for a bug where Java API responses are delayed.",
    "Propose a feature to add Spring Batch for data processing.",
    "Report a bug where the Spring Boot app crashes on configuration reload.",
    "Create an issue for a bug where Java NPE occurs in service layer.",
    "Propose a feature to implement Spring WebFlux for reactive APIs.",
    "Report a bug where the Spring Boot app fails to register with service discovery.",
    "Create an issue for a bug where Java API caching is inconsistent.",
    "Propose a feature to add Spring Cloud Config for externalized config.",
    "Report a bug where the Spring Boot app leaks connections.",
    "Create an issue for a bug where Java API validation fails silently.",
    "Propose a feature to implement Spring Retry for failed operations.",
    "Report a bug where the Spring Boot app crashes on startup.",
    "Create an issue for a bug where Java API endpoints return wrong data.",
    "Propose a feature to add Spring Integration for enterprise messaging.",
    "Report a bug where the Spring Boot app fails to handle timeouts.",
    "Create an issue for a bug where Java memory leaks occur in services.",
    "Propose a feature to implement Spring AOP for logging.",
    "Report a bug where the Spring Boot app drops messages in Kafka.",
    "Create an issue for a bug where Java API security filters fail.",
    "Propose a feature to add Spring Cloud Gateway for routing.",
    "Report a bug where the Spring Boot app fails to scale horizontally.",
    "Create an issue for a bug where Java API responses are truncated.",
    "Propose a feature to implement Spring Data Redis for caching.",
    "Report a bug where the Spring Boot app crashes on shutdown.",
    "Create an issue for a bug where Java API endpoints timeout.",
    "Propose a feature to add Spring Boot Admin for monitoring.",
    "Report a bug where the Spring Boot app fails to handle large payloads.",
    "Create an issue for a bug where Java API authentication fails.",
    "Propose a feature to implement Spring Security OAuth2.",
    "Report a bug where the Spring Boot app leaks threads.",
    "Create an issue for a bug where Java API caching expires prematurely.",
    "Propose a feature to add Spring Cloud Sleuth for tracing.",
    "Report a bug where the Spring Boot app fails to connect to the database.",
    "Create an issue for a bug where Java API responses are malformed.",
    "Propose a feature to implement Spring Boot Actuator health checks.",
    "Report a bug where the Spring Boot app crashes on configuration change.",
    "Create an issue for a bug where Java API endpoints are inaccessible.",
    "Propose a feature to add Spring Data MongoDB for NoSQL.",
    "Report a bug where the Spring Boot app fails to handle exceptions.",
    "Create an issue for a bug where Java API security headers are missing.",
    "Propose a feature to implement Spring Cloud Bus for config updates.",
    "Report a bug where the Spring Boot app crashes on high concurrency.",
    "Create an issue for a bug where Java API responses are slow.",
    "Propose a feature to add Spring Boot Starter for testing.",
    "Report a bug where the Spring Boot app fails to register endpoints.",
    "Create an issue for a bug where Java API caching fails under load.",
    "Propose a feature to implement Spring Security JWT.",
    "Report a bug where the Spring Boot app leaks database connections.",
    "Create an issue for a bug where Java API endpoints return 404.",
    "Propose a feature to add Spring Cloud Contract for testing.",
    "Report a bug where the Spring Boot app fails to handle retries.",
    "Create an issue for a bug where Java API validation throws exceptions.",
    "Propose a feature to implement Spring Boot DevTools.",
    "Report a bug where the Spring Boot app crashes on network disconnect.",
    "Create an issue for a bug where Java API responses are inconsistent.",
    "Propose a feature to add Spring Data REST for APIs.",
    "Report a bug where the Spring Boot app fails to load properties.",
    "Create an issue for a bug where Java API security filters crash.",
    "Propose a feature to implement Spring Cloud LoadBalancer.",
    "Report a bug where the Spring Boot app leaks memory on startup.",
    "Create an issue for a bug where Java API endpoints are duplicated.",
    "Propose a feature to add Spring Boot Starter for WebSocket.",
    "Report a bug where the Spring Boot app fails to handle large requests.",
    "Create an issue for a bug where Java API caching is disabled.",
    "Propose a feature to implement Spring Security LDAP.",
    "Report a bug where the Spring Boot app crashes on session timeout.",
    "Create an issue for a bug where Java API responses are empty.",
    "Propose a feature to add Spring Cloud Stream for messaging.",
    "Report a bug where the Spring Boot app fails to connect to Redis.",
    "Create an issue for a bug where Java API endpoints are slow.",
    "Propose a feature to implement Spring Boot Actuator endpoints.",
    "Report a bug where the Spring Boot app leaks file handles.",
    "Create an issue for a bug where Java API security is bypassed.",
    "Propose a feature to add Spring Data JDBC for relational databases.",
    "Report a bug where the Spring Boot app fails to handle errors.",
    "Create an issue for a bug where Java API responses are corrupted.",
    "Propose a feature to implement Spring Cloud Vault for secrets.",
    "Report a bug where the Spring Boot app crashes on config reload.",
    "Create an issue for a bug where Java API endpoints are unreachable.",
    "Propose a feature to add Spring Boot Starter for GraphQL.",
    "Report a bug where the Spring Boot app fails to scale vertically.",
    "Create an issue for a bug where Java API caching fails silently.",
    "Propose a feature to implement Spring Security SAML.",
    "Report a bug where the Spring Boot app crashes on database failover.",
    "Create an issue for a bug where Java API responses are delayed.",
    "Propose a feature to add Spring Cloud Gateway filters.",
    "Report a bug where the Spring Boot app fails to handle timeouts.",
    "Create an issue for a bug where Java API security headers are invalid.",
    "Propose a feature to implement Spring Boot Starter for R2DBC.",
    "Report a bug where the Spring Boot app leaks connections on shutdown.",
    "Create an issue for a bug where Java API endpoints return errors."
]

# Function to create an issue
def create_issue(title):
    data = {
        "title": title,
        "body": "Please provide steps to reproduce, expected vs actual behavior, and severity. Reported on: 10:19 AM IST, August 07, 2025.",
        "labels": ["bug", "enhancement", "system-design"]
    }
    response = requests.post(API_URL, json=data, headers=HEADERS)
    if response.status_code == 201:
        print(f"Successfully created issue: {title} (ID: {response.json()['number']})")
    else:
        print(f"Failed to create issue {title}: {response.status_code} - {response.text}")

# Check existing issues to avoid duplicates
def get_existing_issue_titles():
    response = requests.get(API_URL, headers=HEADERS, params={"state": "all"})
    if response.status_code == 200:
        return {issue["title"] for issue in response.json()}
    else:
        print(f"Failed to fetch existing issues: {response.status_code} - {response.text}")
        return set()

# Main execution
if __name__ == "__main__":
    if not GITHUB_TOKEN:
        print("Error: GITHUB_TOKEN environment variable not set. Please set it with your GitHub Personal Access Token.")
        exit(1)

    # Get existing issue titles
    existing_titles = get_existing_issue_titles()

    # Create issues, skipping any that already exist
    for title in issues:
        if title not in existing_titles:
            create_issue(title)
            time.sleep(1)  # Rate limiting to avoid hitting API limits (1 request per second)
        else:
            print(f"Skipping existing issue: {title}")

    print("Issue creation process completed.")